# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: PR Checks

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  code_quality_checks:

    continue-on-error: False
    runs-on: ubuntu-18.04
    timeout-minutes: 60

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel
        pip install tox
    - name: Check it can build
      run: ./scripts/install_dependencies.sh


