# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: PR Checks

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  install_dependencies:

    continue-on-error: False
    runs-on: ubuntu-18.04
    timeout-minutes: 60

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel
        pip install tox
    - name: Install dependencies
      run: ./scripts/install_dependencies_18_04.sh
    - name: Install cmake
      run: |
        wget https://github.com/Kitware/CMake/releases/download/v3.19.3/cmake-3.19.3-Linux-x86_64.sh
        mkdir -p "${HOME}"/.local
        bash ./cmake-3.19.3-Linux-x86_64.sh --skip-license --prefix="${HOME}"/.local/
        export PATH=$HOME/.local/bin:$PATH
        cmake --version
        rm cmake-3.19.3-Linux-x86_64.sh
    - name: Build
      run: |
        ls
        mkdir build
        cmake -H. -B ./build -DCMAKE_BUILD_TYPE=Debug -DTESTS=ON -DENABLE_COVERAGE=ON
        cmake --build ./build -- -j2






